-- ============================================================================
-- AMPLIAR MATERIAS DE 10 A 15 POR GRUPO + ALIASES FALTANTES
-- Proyecto: mi-web-escolar (AulaNube / CETAC)
-- Ejecutar en: Supabase SQL Editor
--
-- OBJETIVO:
--   1) Crear las tablas físicas MAT011–MAT015 para los 24 grupos existentes
--      (1RO A–D y 2DO/3RO/4TO/5TO/6TO RH·MECATRONICA A–B) → 24 × 5 = 120 tablas.
--      Hoy cada grupo tiene MAT001–MAT010; se aumenta a 15 (1ROAMAT015, etc.).
--   2) Registrar en el catálogo `materias` las asignaturas nuevas que faltan
--      según «things/CLASES CETAC ACTUALES.txt»:
--        · Taller deportivo       · Taller de tecnología
--        · Taller de arte         · Taller de matemáticas
--        · Taller de vivero
--   3) Vincular la oferta `grupo_materias` (grupo → materia) con su tabla
--      física nueva (tabla_legacy = [GRADO][CARRERA][GRUPO]MAT###).
--   4) Agregar los aliases que faltan en `materias_nombres_visibles`
--      (nombre visible = el nombre real de la clase del archivo).
--
-- ALCANCE DE ALIASES:
--   El archivo CLASES CETAC ACTUALES cubre SOLO 10 grupos:
--     1° A/B/C/D, 3° RH A/B, 3° MC A, 5° RH A/B y 5° MC A.
--   Para esos grupos se crean tabla + oferta + alias de las clases nuevas.
--   Para el resto (2DO/4TO/6TO y grupos «B» no listados) SOLO se crean las
--   tablas físicas; su oferta/alias se agregan con el MISMO patrón cuando el
--   directivo defina su horario (INSERT INTO ... SELECT de la sección 3/4).
--
-- ESTRUCTURA DE TABLA FÍSICA (idéntica a las 240 tablas MAT001–010 existentes):
--   id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
--   alumno_nombre text
--   Las columnas de actividades/calificaciones se agregan dinámicamente al
--   subir el Excel (RPC escolar_sync_columns / escolar_agregar_columnas).
--   RLS: las tablas de materia legacy se dejaron SIN RLS (anon accede por
--   diseño histórico); aquí se replica ese comportamiento.
--
-- IDEMPOTENTE: CREATE IF NOT EXISTS + ON CONFLICT → se puede re-ejecutar.
-- NO borra datos, NO toca tablas existentes, NO altera columnas.
-- ============================================================================

BEGIN;

-- ============================================================================
-- 1) TABLAS FÍSICAS NUEVAS MAT011–MAT015 (24 grupos × 5 = 120 tablas)
-- ----------------------------------------------------------------------------
-- Regla de nombre (C4.28): [GRADO][CARRERA][GRUPO]MAT###
--   GRADO  → 1RO, 2DO, 3RO, 4TO, 5TO, 6TO
--   CARRERA→ MECATRONICA = MC, RH = RH (1RO sin carrera)
--   GRUPO  → A, B (C, D solo en 1RO)
-- MAT### NO significa la materia: es SOLO el ID técnico.
-- ============================================================================
DO $$
DECLARE
  prefijo text;
  num integer;
  nombre_tabla text;
BEGIN
  FOREACH prefijo IN ARRAY ARRAY[
    '1ROA', '1ROB', '1ROC', '1ROD',
    '2DOMCA', '2DORHA', '2DOMCB', '2DORHB',
    '3ROMCA', '3RORHA', '3ROMCB', '3RORHB',
    '4TOMCA', '4TORHA', '4TOMCB', '4TORHB',
    '5TOMCA', '5TORHA', '5TOMCB', '5TORHB',
    '6TOMCA', '6TORHA', '6TOMCB', '6TORHB'
  ]
  LOOP
    FOR num IN 11..15 LOOP
      nombre_tabla := prefijo || 'MAT' || lpad(num::text, 3, '0');
      EXECUTE format(
        'CREATE TABLE IF NOT EXISTS public.%I (
           id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
           alumno_nombre text
         )',
        nombre_tabla
      );
      RAISE NOTICE 'Tabla creada: %', nombre_tabla;
    END LOOP;
  END LOOP;
END $$;

-- ============================================================================
-- 2) CATÁLOGO `materias` — asignaturas nuevas (clave UNIQUE, idempotente)
-- ============================================================================
INSERT INTO public.materias (clave, nombre, activo)
VALUES
  ('TALLER DEPORTIVO', 'TALLER DEPORTIVO', true),
  ('TALLER DE TECNOLOGIA', 'TALLER DE TECNOLOGIA', true),
  ('TALLER DE ARTE', 'TALLER DE ARTE', true),
  ('TALLER DE MATEMATICAS', 'TALLER DE MATEMATICAS', true),
  ('TALLER DE VIVERO', 'TALLER DE VIVERO', true)
ON CONFLICT (clave) DO UPDATE
  SET nombre = EXCLUDED.nombre,
      activo = true;

-- ============================================================================
-- 3) OFERTA `grupo_materias` — las materias nuevas de los 10 grupos del
--    archivo CLASES CETAC ACTUALES, apuntando a su tabla física nueva.
-- ----------------------------------------------------------------------------
-- Fuente (orden del archivo):
--   1° A → Taller deportivo, Taller de tecnología
--   1° B → Taller deportivo, Taller de tecnología
--   1° C → Taller de tecnología, Taller deportivo
--   1° D → Taller de arte, Taller de matemáticas, Taller de tecnología
--   3° MC A → Taller de vivero
--   5° RH A / 5° RH B / 5° MC A → Taller deportivo
-- ============================================================================
INSERT INTO public.grupo_materias (grupo_id, materia_id, tabla_legacy, activo)
SELECT g.id, m.id, v.tabla_legacy, true
FROM (VALUES
  ('1RO'::text, 'A'::text, NULL::text, 'TALLER DEPORTIVO'::text,     '1ROAMAT011'::text),
  ('1RO'::text, 'A'::text, NULL::text, 'TALLER DE TECNOLOGIA'::text, '1ROAMAT012'::text),
  ('1RO'::text, 'B'::text, NULL::text, 'TALLER DEPORTIVO'::text,     '1ROBMAT011'::text),
  ('1RO'::text, 'B'::text, NULL::text, 'TALLER DE TECNOLOGIA'::text, '1ROBMAT012'::text),
  ('1RO'::text, 'C'::text, NULL::text, 'TALLER DE TECNOLOGIA'::text, '1ROCMAT011'::text),
  ('1RO'::text, 'C'::text, NULL::text, 'TALLER DEPORTIVO'::text,     '1ROCMAT012'::text),
  ('1RO'::text, 'D'::text, NULL::text, 'TALLER DE ARTE'::text,       '1RODMAT011'::text),
  ('1RO'::text, 'D'::text, NULL::text, 'TALLER DE MATEMATICAS'::text,'1RODMAT012'::text),
  ('1RO'::text, 'D'::text, NULL::text, 'TALLER DE TECNOLOGIA'::text, '1RODMAT013'::text),
  ('3RO'::text, 'A'::text, 'MECATRONICA'::text, 'TALLER DE VIVERO'::text, '3ROMCAMAT011'::text),
  ('5TO'::text, 'A'::text, 'RH'::text, 'TALLER DEPORTIVO'::text,     '5TORHAMAT011'::text),
  ('5TO'::text, 'B'::text, 'RH'::text, 'TALLER DEPORTIVO'::text,     '5TORHBMAT011'::text),
  ('5TO'::text, 'A'::text, 'MECATRONICA'::text, 'TALLER DEPORTIVO'::text, '5TOMCAMAT011'::text)
) AS v(grado, nombre, carrera_clave, materia_clave, tabla_legacy)
JOIN public.grupos g
  ON g.grado = v.grado
 AND g.nombre = v.nombre
 AND g.carrera_id IS NOT DISTINCT FROM (
       SELECT c.id FROM public.carreras c WHERE c.clave = v.carrera_clave
     )
JOIN public.materias m ON m.clave = v.materia_clave
ON CONFLICT (grupo_id, materia_id) DO UPDATE
  SET tabla_legacy = EXCLUDED.tabla_legacy,
      activo = true;

-- ============================================================================
-- 4) ALIASES FALTANTES — materias_nombres_visibles (nombre visible real)
--    fuente: things/CLASES CETAC ACTUALES.txt
-- ============================================================================
INSERT INTO public.materias_nombres_visibles (materia_id, nombre_visible, activo, actualizado_por)
SELECT v.materia_id, v.nombre_visible, true, 'sql-ampliar-15-aliases'
FROM (VALUES
  ('1ROAMAT011'::text,   'Taller deportivo'::text),
  ('1ROAMAT012'::text,   'Taller de tecnología'::text),
  ('1ROBMAT011'::text,   'Taller deportivo'::text),
  ('1ROBMAT012'::text,   'Taller de tecnología'::text),
  ('1ROCMAT011'::text,   'Taller de tecnología'::text),
  ('1ROCMAT012'::text,   'Taller deportivo'::text),
  ('1RODMAT011'::text,   'Taller de arte'::text),
  ('1RODMAT012'::text,   'Taller de matemáticas'::text),
  ('1RODMAT013'::text,   'Taller de tecnología'::text),
  ('3ROMCAMAT011'::text, 'Taller de vivero'::text),
  ('5TORHAMAT011'::text, 'Taller deportivo'::text),
  ('5TORHBMAT011'::text, 'Taller deportivo'::text),
  ('5TOMCAMAT011'::text, 'Taller deportivo'::text)
) AS v(materia_id, nombre_visible)
ON CONFLICT (materia_id) DO UPDATE
  SET nombre_visible = EXCLUDED.nombre_visible,
      activo = true,
      updated_at = now(),
      actualizado_por = 'sql-ampliar-15-aliases';

-- ============================================================================
-- 5) VALIDACIÓN POST-APLICACIÓN
-- ============================================================================
DO $$
DECLARE
  n int;
BEGIN
  SELECT count(*) INTO n
  FROM information_schema.tables
  WHERE table_schema = 'public'
    AND table_name ~ '^(1RO|2DO|3RO|4TO|5TO|6TO)(MC|RH)?[A-D]MAT(01[1-5])$';
  RAISE NOTICE 'VALIDACIÓN: tablas físicas MAT011–MAT015 → % (esperado 120)', n;

  SELECT count(*) INTO n
  FROM information_schema.tables
  WHERE table_schema = 'public'
    AND table_name ~ '^(1RO|2DO|3RO|4TO|5TO|6TO)(MC|RH)?[A-D]MAT[0-9]{3}$';
  RAISE NOTICE 'VALIDACIÓN: total tablas físicas de materia → % (esperado 360)', n;

  SELECT count(*) INTO n
  FROM public.materias
  WHERE clave IN ('TALLER DEPORTIVO','TALLER DE TECNOLOGIA','TALLER DE ARTE',
                  'TALLER DE MATEMATICAS','TALLER DE VIVERO');
  RAISE NOTICE 'VALIDACIÓN: asignaturas nuevas en catálogo → % (esperado 5)', n;

  SELECT count(*) INTO n
  FROM public.grupo_materias
  WHERE tabla_legacy ~ 'MAT(01[1-5])$';
  RAISE NOTICE 'VALIDACIÓN: grupo_materias con tabla nueva → % (esperado 13)', n;

  SELECT count(*) INTO n
  FROM public.materias_nombres_visibles
  WHERE materia_id ~ 'MAT(01[1-5])$';
  RAISE NOTICE 'VALIDACIÓN: aliases MAT011–015 → % (esperado 13)', n;

  -- Cada alias nuevo debe apuntar a una tabla física existente.
  SELECT count(*) INTO n
  FROM public.materias_nombres_visibles mnv
  WHERE mnv.materia_id ~ 'MAT(01[1-5])$'
    AND to_regclass(format('public.%I', mnv.materia_id)) IS NULL;
  RAISE NOTICE 'VALIDACIÓN: aliases MAT011–015 sin tabla física → % (esperado 0)', n;
END $$;

COMMIT;